# Assignment 9

### Task 1: Create Numpy Array

In [6]:
import numpy as np
aoned = np.arange(1, 11)
print(aoned)
print(aoned.shape)
atwod = aoned[:9].reshape(3, 3)
print(atwod)
print(atwod.shape)
alist_array = np.array([10, 20, 30, 40, 50])
print(alist_array)
print(alist_array.shape)

[ 1  2  3  4  5  6  7  8  9 10]
(10,)
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
[10 20 30 40 50]
(5,)


### Task 2: Important Mathmetical Operation

In [9]:
A = np.array([10,20,30,40])
B = np.array([1,2,3,4])
added = A + B
print(added)
subtracted = A - B
print(subtracted)
multiplied = A * B
print(multiplied)
divided = A / B
print(divided)
power = A ** 2
print(power)
#-------By Using Numpy Functions-------
print("Using Numpy Functions:")
added_func = np.add(A, B)
print(added_func)
subtracted_func = np.subtract(A, B)
print(subtracted_func)
multiplied_func = np.multiply(A, B)
print(multiplied_func)
divided_func = np.divide(A, B)
print(divided_func)
power_func = np.power(A, 2)
print(power_func)

[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]
Using Numpy Functions:
[11 22 33 44]
[ 9 18 27 36]
[ 10  40  90 160]
[10. 10. 10. 10.]
[ 100  400  900 1600]


### Task 3: Important Numpy Mathmatical Function

In [10]:
values = np.array([2,4,6,8,10])
sqrt_values = np.sqrt(values)
print("Square Root:", sqrt_values)
exp_values = np.exp(values)
print("Exponential:", exp_values)
log_values = np.log(values)
print("Logarithm:", log_values)
sum_values = np.sum(values)
print("Sum:", sum_values)
cumsum_values = np.cumsum(values)
print("Cumulative Sum:", cumsum_values)


Square Root: [1.41421356 2.         2.44948974 2.82842712 3.16227766]
Exponential: [7.38905610e+00 5.45981500e+01 4.03428793e+02 2.98095799e+03
 2.20264658e+04]
Logarithm: [0.69314718 1.38629436 1.79175947 2.07944154 2.30258509]
Sum: 30
Cumulative Sum: [ 2  6 12 20 30]


### Task 4: Aggreation Operation 

In [12]:
data = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])
row_sum1 = np.sum(data, axis=1)
print("Row-wise Sum:", row_sum1)
col_sum1 = np.sum(data, axis=0)
print("Column-wise Sum:", col_sum1)
min_value = np.min(data)
print("Minimum Value:", min_value)
max_value = np.max(data)
print("Maximum Value:", max_value)
mean_value = np.mean(data)  
print("Overall Mean:", mean_value)


Row-wise Sum: [ 60 150 240]
Column-wise Sum: [120 150 180]
Minimum Value: 10
Maximum Value: 90
Overall Mean: 50.0


### Task 5: Statistical Oprations

In [13]:
marks = np.array([78,85,90,66,72,88,95,60])
mean_marks = np.mean(marks)
print("Mean Marks:", mean_marks)
median_marks = np.median(marks)
print("Median Marks:", median_marks)
variance_marks = np.var(marks)
print("Variance of Marks:", variance_marks)
std_dev_marks = np.std(marks)
print("Standard Deviation of Marks:", std_dev_marks)
minimum_marks = np.min(marks)
print("Minimum Marks:", minimum_marks)
maximum_marks = np.max(marks)
print("Maximum Marks:", maximum_marks)
range_marks = maximum_marks - minimum_marks
print("Range of Marks:", range_marks)

Mean Marks: 79.25
Median Marks: 81.5
Variance of Marks: 134.1875
Standard Deviation of Marks: 11.583932838203095
Minimum Marks: 60
Maximum Marks: 95
Range of Marks: 35


### Task 6: Percentiles and Sorting

In [20]:
sorted_marks = np.sort(marks)
print("Sorted Marks:", sorted_marks)
percentiles = np.percentile(marks, [25, 50, 75])
print("25th, 50th, 75th Percentiles:", percentiles)
avarage_marks = np.mean(marks)
print("Average Marks:", avarage_marks)
above_average_count = np.sum(marks > avarage_marks)
print("Count of Marks Above Average:", above_average_count)


Sorted Marks: [60 66 72 78 85 88 90 95]
25th, 50th, 75th Percentiles: [70.5 81.5 88.5]
Average Marks: 79.25
Count of Marks Above Average: 4


### Task 7: Mini Use Case (Sales Analysis)

In [22]:
sales = np.array([1200,1500,900,2000,1800,1700,1600])
total_sales = np.sum(sales)
print("Total Weekly Sales:", total_sales)
average_sales = np.mean(sales)
print("Average Daily Sales:", average_sales)
highest_sales = np.max(sales)
print("Highest Sales in a Day:", highest_sales)
lowest_sales = np.min(sales)
print("Lowest Sales in a Day:", lowest_sales)
std_dev_sales = np.std(sales)
print("Standard Deviation of Sales:", std_dev_sales)
above_average_sales = np.sum(sales > average_sales)
print("Number of Days with Sales Above Average:", above_average_sales)

Total Weekly Sales: 10700
Average Daily Sales: 1528.5714285714287
Highest Sales in a Day: 2000
Lowest Sales in a Day: 900
Standard Deviation of Sales: 345.2298849598449
Number of Days with Sales Above Average: 4
